version: '3.8'

services:
  frontend:
    container_name: websocket-demo-fe
    build:
      context: frontend
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
  backend:
    container_name: websocket-demo-be
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
